### PR TITLE
part 5 booking page

### PR DESCRIPTION
**Pull request by jaxineC**
Hi,
part 5 is done, please review my code, thank you.
signup for a new user or using email: jx@gmail.com, pw: 0000

http://52.20.252.232:3000/
http://52.20.252.232:3000/attraction/5
http://52.20.252.232:3000/booking

### CODE REVIEW

**Comment by cwpeng** [comment]
Your booking.html will show "您好，undefined，待預訂的行程如下：" where undefined should be user's name.

**Comment by jaxineC** [comment]
Couldn't find the issue you mentioned to fix it.
However, in my db, there is a "undefined" user, do you mean to verify a user ender his name on signup?
4 | undefined              | ply@ply.com    | ply 
image

https://www.dropbox.com/s/trgza0hprtqixex/Screenshot%20%28230%29.png?dl=0
https://www.dropbox.com/s/z3im45jlwi50ocv/Screenshot%20%28229%29.png?dl=0

**Review by cwpeng — APPROVED** [review]
OHOH, I see, my name is undefined. It's OK for now. But I'm curious why my name is undefined because I enter ply as name when I sign up.

**Comment by jaxineC** [comment]
The project is telling me to learn validating user input :) Thank you.

**Pull request merged**
