### PR TITLE
Hw part3 done for review

### PR DESCRIPTION
**Pull request by jaxineC**
http://52.20.252.232:3000/
Jaxine Chang (Chia Hsing Chang)

### CODE REVIEW

**Comment by cwpeng** [comment]
When I search 館, there should be 2 pages in total. but your code only show first page of data.

Fix issue and leave comment for me to review again.

**Comment by jaxineC** [comment]
http://52.20.252.232:3000/
fixed scroll down for more content in search result,
please review again, thank you.

**Comment by jaxineC** [comment]
http://52.20.252.232:3000/
Fixed scroll-down for more search results and others,
please review again, thank you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
