### PR TITLE
作業繳交

### PR DESCRIPTION
**Pull request by jaxineC**
張家馨 Jaxine
http://52.20.252.232:3000/api/attractions?page=1
http://52.20.252.232:3000/api/attractions?page=0&keyword=%E8%97%9D%E8%A1%93
http://52.20.252.232:3000/api/attraction/100

### CODE REVIEW

**Comment by cwpeng** [comment]
1. page input should start from 0, not 1, according API spec.
2. "images" field should be an array containing image URLs separately, not a string.
3. response format of http://52.20.252.232:3000/api/attraction/10 is not incorrect, check API carefully.

Fix issues and leave comment for me to review again.

**Comment by jaxineC** [comment]
1.fixed  starting page by => input_page= request.args.get('page',0) 
2.fixed string to list by => eval()+replace() for return value
3.fiexed 2nd API format by => result[0] in return value

**Comment by cwpeng** [comment]
1. We should start from 0, and then 1, 2, 3, 4, ... Your result is actually start from 1, and then 2, 3, 4, 5, ... page 0 is just the same with 1. It's not start from 0.
2. OK.
3. OK.

Fix issue and leave comment for me to review again.

**Comment by jaxineC** [comment]
1. fixed page issue, starting from 0, by => int(input_page) starts from 0

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
